//Tasks

export const SET_SELECTED_TASK = "SET_SELECTED_TASK";
export const SET_SELECTED_FILES = "SET_SELECTED_FILES";
export const ADD_SELECTED_FILES = "ADD_SELECTED_FILES";
export const UPLOAD_FILES = "UPLOAD_FILES";
export const DOWNLOAD_FILE = "DOWNLOAD_FILE";
export const DELETE_FILE = "DELETE_FILE";

//Subtasks
export const LOAD_SUBTASKS_START = "LOAD_SUBTASKS_START";
export const LOAD_SUBTASKS_SUCCESS = "LOAD_SUBTASKS_SUCCESS";
export const LOAD_SUBTASKS_ERROR = "LOAD_SUBTASKS_ERROR";

export const CREATE_SUBTASKS_START = "CREATE_SUBTASKS_START";
export const CREATE_SUBTASKS_SUCCESS = "CREATE_SUBTASKS_SUCCESS";
export const CREATE_SUBTASKS_ERROR = "CREATE_SUBTASKS_ERROR";

export const DONE_SUBTASKS_START = "DONE_SUBTASKS_START";
export const DONE_SUBTASKS_SUCCESS = "DONE_SUBTASKS_SUCCESS";
export const DONE_SUBTASKS_ERROR = "DONE_SUBTASKS_ERROR";

export const DELETE_SUBTASKS_START = "DELETE_SUBTASKS_START";
export const DELETE_SUBTASKS_SUCCESS = "DELETE_SUBTASKS_SUCCESS";
export const DELETE_SUBTASKS_ERROR = "DELETE_SUBTASKS_ERROR";

export const LOAD_COMMENTS_START = "LOAD_COMMENTS_START";
export const LOAD_COMMENTS_SUCCESS = "LOAD_COMMENTS_SUCCESS";
export const LOAD_COMMENTS_ERROR = "LOAD_COMMENTS_ERROR";

export const CREATE_COMMENTS_START = "CREATE_COMMENTS_START";
export const CREATE_COMMENTS_SUCCESS = "CREATE_COMMENTS_SUCCESS";
export const CREATE_COMMENTS_ERROR = "CREATE_COMMENTS_ERROR";
