export const GET_PROJECTS = "GET_PROJECTS";
export const GET_TASKS = "GET_TASKS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const SET_PROJECTS = "SET_PROJECTS";
